// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityCrud.Server.DAL;

#nullable disable

namespace UniversityCrud.Server.Migrations
{
    [DbContext(typeof(UniversityDBContext))]
    [Migration("20230327111832_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityCrud.Shared.Model.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 3, 27, 16, 48, 32, 293, DateTimeKind.Local).AddTicks(5660),
                            DateUpdated = new DateTime(2023, 3, 27, 16, 48, 32, 293, DateTimeKind.Local).AddTicks(5690),
                            Description = "Department of Information Technology",
                            IsActive = true,
                            Title = "Information Technology"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 3, 27, 16, 48, 32, 293, DateTimeKind.Local).AddTicks(5690),
                            DateUpdated = new DateTime(2023, 3, 27, 16, 48, 32, 293, DateTimeKind.Local).AddTicks(5690),
                            Description = "Department of Information Technology and Management",
                            IsActive = true,
                            Title = "Information Technology and Management"
                        });
                });

            modelBuilder.Entity("UniversityCrud.Shared.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 100000,
                            CourseId = 1,
                            DateCreated = new DateTime(2023, 3, 27, 16, 48, 32, 293, DateTimeKind.Local).AddTicks(5760),
                            DateOfBirth = new DateTime(1992, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2023, 3, 27, 16, 48, 32, 293, DateTimeKind.Local).AddTicks(5760),
                            Email = "rpathithasan0@gmail.com",
                            FirstName = "Pathithasan",
                            IsActive = true,
                            LastName = "Rajakopal"
                        });
                });

            modelBuilder.Entity("UniversityCrud.Shared.Model.Student", b =>
                {
                    b.HasOne("UniversityCrud.Shared.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });
#pragma warning restore 612, 618
        }
    }
}
